# Generated by Django 5.1.5 on 2025-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_rename_pucture_page_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='body',
        ),
        migrations.RemoveField(
            model_name='page',
            name='picture',
        ),
        migrations.AddField(
            model_name='page',
            name='a1',
            field=models.TextField(default='', max_length=2000, verbose_name='回答1'),
        ),
        migrations.AddField(
            model_name='page',
            name='a10',
            field=models.TextField(default='', max_length=2000, verbose_name='回答10'),
        ),
        migrations.AddField(
            model_name='page',
            name='a2',
            field=models.TextField(default='', max_length=2000, verbose_name='回答2'),
        ),
        migrations.AddField(
            model_name='page',
            name='a3',
            field=models.TextField(default='', max_length=2000, verbose_name='回答3'),
        ),
        migrations.AddField(
            model_name='page',
            name='a4',
            field=models.TextField(default='', max_length=2000, verbose_name='回答4'),
        ),
        migrations.AddField(
            model_name='page',
            name='a5',
            field=models.TextField(default='', max_length=2000, verbose_name='回答5'),
        ),
        migrations.AddField(
            model_name='page',
            name='a6',
            field=models.TextField(default='', max_length=2000, verbose_name='回答6'),
        ),
        migrations.AddField(
            model_name='page',
            name='a7',
            field=models.TextField(default='', max_length=2000, verbose_name='回答7'),
        ),
        migrations.AddField(
            model_name='page',
            name='a8',
            field=models.TextField(default='', max_length=2000, verbose_name='回答8'),
        ),
        migrations.AddField(
            model_name='page',
            name='a9',
            field=models.TextField(default='', max_length=2000, verbose_name='回答9'),
        ),
        migrations.AddField(
            model_name='page',
            name='q1',
            field=models.CharField(default='', max_length=100, verbose_name='質問1'),
        ),
        migrations.AddField(
            model_name='page',
            name='q10',
            field=models.CharField(default='', max_length=100, verbose_name='質問10'),
        ),
        migrations.AddField(
            model_name='page',
            name='q2',
            field=models.CharField(default='', max_length=100, verbose_name='質問2'),
        ),
        migrations.AddField(
            model_name='page',
            name='q3',
            field=models.CharField(default='', max_length=100, verbose_name='質問3'),
        ),
        migrations.AddField(
            model_name='page',
            name='q4',
            field=models.CharField(default='', max_length=100, verbose_name='質問4'),
        ),
        migrations.AddField(
            model_name='page',
            name='q5',
            field=models.CharField(default='', max_length=100, verbose_name='質問5'),
        ),
        migrations.AddField(
            model_name='page',
            name='q6',
            field=models.CharField(default='', max_length=100, verbose_name='質問6'),
        ),
        migrations.AddField(
            model_name='page',
            name='q7',
            field=models.CharField(default='', max_length=100, verbose_name='質問7'),
        ),
        migrations.AddField(
            model_name='page',
            name='q8',
            field=models.CharField(default='', max_length=100, verbose_name='質問8'),
        ),
        migrations.AddField(
            model_name='page',
            name='q9',
            field=models.CharField(default='', max_length=100, verbose_name='質問9'),
        ),
    ]
