# Generated by Django 5.1.5 on 2025-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_remove_page_body_remove_page_picture_page_a1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日付'),
        ),
    ]
