# Generated by Django 5.1.5 on 2025-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_page_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='q10',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問10'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問3'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問4'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問5'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問6'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q7',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問7'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q8',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問8'),
        ),
        migrations.AlterField(
            model_name='page',
            name='q9',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='質問9'),
        ),
    ]
