# Generated by Django 5.1.5 on 2025-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_page_answertf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='Answertf',
            field=models.BooleanField(default=False, editable=False, verbose_name='回答'),
        ),
    ]
