# Generated by Django 5.1.5 on 2025-01-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_page_answertf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Answertf',
            new_name='answertf',
        ),
    ]
