# Generated by Django 5.1.5 on 2025-01-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_rename_answertf_page_answertf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='answertf',
            field=models.BooleanField(default=False, verbose_name='回答'),
        ),
    ]
