# Generated by Django 5.1.5 on 2025-01-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_alter_page_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='creator',
        ),
    ]
