# Generated by Django 5.1.5 on 2025-01-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_rename_answered_by_page_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='original_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='diary.page'),
        ),
    ]
